import type { ListingCardData } from "@/types";

/**
 * Demo listings used ONLY as a graceful fallback when DATABASE_URL is not yet
 * configured (first local run before Supabase setup). Once the DB is wired and
 * seeded, real data replaces these automatically. Images point to Unsplash.
 */
export const DEMO_LISTINGS: ListingCardData[] = [
  {
    id: "demo-1",
    title: "iPhone 14 Pro Max 256GB",
    price: 3_000_000,
    negotiable: true,
    city: "Kigali",
    district: "Gasabo",
    neighborhood: "Kimihurura",
    createdAt: new Date(Date.now() - 2 * 3600_000),
    status: "ACTIVE",
    coverImage: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=600&q=70",
    category: { slug: "phones", name: "Phones", icon: "📱" },
    distanceKm: 3,
    featured: true,
  },
  {
    id: "demo-2",
    title: "Toyota Axio 2018 — Very Clean",
    price: 30_000_000,
    negotiable: true,
    city: "Kigali",
    district: "Gasabo",
    neighborhood: "KABC",
    createdAt: new Date(Date.now() - 20 * 60_000),
    status: "ACTIVE",
    coverImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=70",
    category: { slug: "cars", name: "Cars", icon: "🚗" },
    distanceKm: 0.45,
  },
  {
    id: "demo-3",
    title: "A modern studio for rent",
    price: 200_000,
    negotiable: false,
    city: "Kigali",
    district: "Kicukiro",
    neighborhood: "Kanombe",
    createdAt: new Date(Date.now() - 3 * 86400_000),
    status: "ACTIVE",
    coverImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=70",
    category: { slug: "rentals", name: "Rentals", icon: "🏠" },
    distanceKm: 15,
  },
  {
    id: "demo-4",
    title: "Dell XPS 13 Laptop",
    price: 110_000,
    negotiable: true,
    city: "Kigali",
    district: "Nyarugenge",
    neighborhood: "Kiyovu",
    createdAt: new Date(Date.now() - 10 * 86400_000),
    status: "ACTIVE",
    coverImage: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=70",
    category: { slug: "electronics", name: "Electronics", icon: "💻" },
    distanceKm: 6,
  },
  {
    id: "demo-5",
    title: "Sofa set 7 seater — Like New",
    price: 450_000,
    negotiable: true,
    city: "Kigali",
    district: "Kicukiro",
    neighborhood: "Niboye",
    createdAt: new Date(Date.now() - 3 * 86400_000),
    status: "ACTIVE",
    coverImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=70",
    category: { slug: "furniture", name: "Furniture", icon: "🛋️" },
    distanceKm: 9,
  },
  {
    id: "demo-6",
    title: "Samsung Galaxy S23 Ultra",
    price: 610_000,
    negotiable: true,
    city: "Kigali",
    district: "Gasabo",
    neighborhood: "Remera",
    createdAt: new Date(Date.now() - 6 * 3600_000),
    status: "ACTIVE",
    coverImage: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=70",
    category: { slug: "phones", name: "Phones", icon: "📱" },
    distanceKm: 4,
  },
];

export const USING_DEMO_DATA = !process.env.DATABASE_URL;
