import { Listing } from './types';

const placeholderImage = (category: string, id: number) =>
  `https://picsum.photos/400/300?random=${category}${id}`;

export const mockListings: Listing[] = [
  // Phones (5)
  {
    id: '1',
    title: 'iPhone 13 Pro Max - Excellent Condition',
    price: 1200000,
    currency: 'Frw',
    category: 'phones',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('phone', 1)],
    description: 'Mint condition, all accessories included, no scratches.',
    seller: { name: 'Alice Uwimana', phone: '+25078123456', joinedDate: '2024-01-15' },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2h ago
    isBoosted: true,
    viewCount: 234,
  },
  {
    id: '2',
    title: 'Samsung Galaxy S21 Ultra',
    price: 950000,
    currency: 'Frw',
    category: 'phones',
    condition: 'refurbished',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('phone', 2)],
    description: 'Refurbished by official Samsung, 1 year warranty.',
    seller: { name: 'Jean Claude', phone: '+25079987654', joinedDate: '2023-06-10' },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 128,
  },
  {
    id: '3',
    title: 'OnePlus 10 Pro - Brand New',
    price: 750000,
    currency: 'Frw',
    category: 'phones',
    condition: 'new',
    location: 'Kigali, Gasabo',
    images: [placeholderImage('phone', 3)],
    description: 'Sealed box, never opened, with warranty.',
    seller: { name: 'Marie Nabukenya', phone: '+25072555666', joinedDate: '2025-11-20' },
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 89,
  },
  {
    id: '4',
    title: 'Xiaomi Redmi Note 12 - Good Condition',
    price: 450000,
    currency: 'Frw',
    category: 'phones',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('phone', 4)],
    description: 'Works perfectly, minor cosmetic scratches on back.',
    seller: { name: 'Kwame Mensah', phone: '+25073444555', joinedDate: '2024-08-02' },
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 156,
  },
  {
    id: '5',
    title: 'iPhone 12 - Fast Charger Included',
    price: 850000,
    currency: 'Frw',
    category: 'phones',
    condition: 'used',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('phone', 5)],
    description: 'Battery health at 92%, no damage, all original accessories.',
    seller: { name: 'Amara Diallo', phone: '+25074666777', joinedDate: '2024-03-30' },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 203,
  },

  // Cars (3)
  {
    id: '6',
    title: '2019 Toyota Wish - Low Mileage',
    price: 22000000,
    currency: 'Frw',
    category: 'cars',
    condition: 'used',
    location: 'Kigali, Gasabo',
    images: [placeholderImage('car', 1)],
    description: '45,000 km only, full service history, no accidents.',
    seller: { name: 'Darius Kumala', phone: '+25075888999', joinedDate: '2023-12-10' },
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 512,
  },
  {
    id: '7',
    title: '2020 Honda Fit - Fuel Efficient',
    price: 18500000,
    currency: 'Frw',
    category: 'cars',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('car', 2)],
    description: 'Perfect for city driving, excellent condition throughout.',
    seller: { name: 'Fidel Nkomo', phone: '+25076111222', joinedDate: '2024-02-14' },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 289,
  },
  {
    id: '8',
    title: '2018 Hyundai Tucson - Automatic',
    price: 15000000,
    currency: 'Frw',
    category: 'cars',
    condition: 'used',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('car', 3)],
    description: 'Well maintained, regular oil changes, all features working.',
    seller: { name: 'Esther Makwaya', phone: '+25077333444', joinedDate: '2024-05-22' },
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 178,
  },

  // Houses (4)
  {
    id: '9',
    title: '3-Bedroom House in Gacuriro',
    price: 850000000,
    currency: 'Frw',
    category: 'houses',
    condition: 'used',
    location: 'Kigali, Gasabo',
    images: [placeholderImage('house', 1)],
    description: 'Modern design, gated compound, reliable water/electricity supply.',
    seller: { name: 'Patrick Habamukiza', phone: '+25078555666', joinedDate: '2023-09-05' },
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 789,
  },
  {
    id: '10',
    title: '2-Bedroom Apartment in Nyarugenge',
    price: 450000000,
    currency: 'Frw',
    category: 'houses',
    condition: 'new',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('house', 2)],
    description: 'New residential complex, fully furnished, proximity to amenities.',
    seller: { name: 'Zainab Habimana', phone: '+25079777888', joinedDate: '2025-01-10' },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 456,
  },
  {
    id: '11',
    title: '4-Bedroom Villa in Kicukiro',
    price: 1200000000,
    currency: 'Frw',
    category: 'houses',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('house', 3)],
    description: 'Spacious villa with swimming pool, garden, ideal for families.',
    seller: { name: 'Umutesi Grace', phone: '+25074999111', joinedDate: '2024-04-15' },
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 634,
  },
  {
    id: '12',
    title: '1-Bedroom Studio in Central Kigali',
    price: 280000000,
    currency: 'Frw',
    category: 'houses',
    condition: 'used',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('house', 4)],
    description: 'Compact and convenient, perfect for students or young professionals.',
    seller: { name: 'Samuel Karanja', phone: '+25075222333', joinedDate: '2024-07-18' },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 321,
  },

  // Furniture (4)
  {
    id: '13',
    title: 'Leather Sofa Set - Modern Design',
    price: 1200000,
    currency: 'Frw',
    category: 'furniture',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('furniture', 1)],
    description: '3-seater + 2 armchairs, very comfortable, minimal wear.',
    seller: { name: 'Rachel Mwangi', phone: '+25076444555', joinedDate: '2024-10-08' },
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 95,
  },
  {
    id: '14',
    title: 'Wooden Dining Table with 6 Chairs',
    price: 650000,
    currency: 'Frw',
    category: 'furniture',
    condition: 'new',
    location: 'Kigali, Gasabo',
    images: [placeholderImage('furniture', 2)],
    description: 'Solid wood, hand-crafted, assembled and ready to use.',
    seller: { name: 'Bertrand Kagali', phone: '+25072666777', joinedDate: '2024-09-12' },
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 167,
  },
  {
    id: '15',
    title: 'Office Desk - Height Adjustable',
    price: 380000,
    currency: 'Frw',
    category: 'furniture',
    condition: 'used',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('furniture', 3)],
    description: 'Electric height adjustment, spacious workspace, excellent condition.',
    seller: { name: 'Nicole Habimana', phone: '+25074888999', joinedDate: '2025-02-03' },
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 112,
  },
  {
    id: '16',
    title: 'Queen Size Bed Frame + Mattress',
    price: 850000,
    currency: 'Frw',
    category: 'furniture',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('furniture', 4)],
    description: 'Sturdy frame, medium-firm mattress, very comfortable sleep.',
    seller: { name: 'Alphonce Mwase', phone: '+25075111222', joinedDate: '2024-06-20' },
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 203,
  },

  // Electronics (4)
  {
    id: '17',
    title: 'MacBook Pro 15" - M1 Chip',
    price: 2800000,
    currency: 'Frw',
    category: 'electronics',
    condition: 'used',
    location: 'Kigali, Gasabo',
    images: [placeholderImage('electronics', 1)],
    description: 'Powerful for work and creative tasks, barely used, original charger.',
    seller: { name: 'Timothy Ochieng', phone: '+25073999444', joinedDate: '2023-11-17' },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 445,
  },
  {
    id: '18',
    title: '65" 4K Smart TV - Samsung',
    price: 1600000,
    currency: 'Frw',
    category: 'electronics',
    condition: 'used',
    location: 'Kigali, Kicukiro',
    images: [placeholderImage('electronics', 2)],
    description: 'Crystal clear picture, built-in streaming apps, excellent sound.',
    seller: { name: 'Victoria Aremu', phone: '+25076555666', joinedDate: '2024-08-25' },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 267,
  },
  {
    id: '19',
    title: 'Canon EOS Rebel Camera + Lens',
    price: 900000,
    currency: 'Frw',
    category: 'electronics',
    condition: 'used',
    location: 'Kigali, Nyarugenge',
    images: [placeholderImage('electronics', 3)],
    description: 'DSLR with 18-55mm lens, perfect for photography beginners.',
    seller: { name: 'David Kipchoge', phone: '+25074666777', joinedDate: '2024-12-01' },
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    isBoosted: false,
    viewCount: 178,
  },
  {
    id: '20',
    title: 'AirPods Pro - Original Apple',
    price: 450000,
    currency: 'Frw',
    category: 'electronics',
    condition: 'new',
    location: 'Kigali, Gasabo',
    images: [placeholderImage('electronics', 4)],
    description: 'Never used, sealed in original box, 2-year warranty card included.',
    seller: { name: 'Hilda Mwangi', phone: '+25072777888', joinedDate: '2025-03-10' },
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isBoosted: true,
    viewCount: 89,
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'phones', label: 'Phones' },
  { id: 'cars', label: 'Cars' },
  { id: 'houses', label: 'Houses' },
  { id: 'furniture', label: 'Furniture' },
  { id: 'electronics', label: 'Electronics' },
];

export const LOCATIONS = [
  'Kigali, Kicukiro',
  'Kigali, Nyarugenge',
  'Kigali, Gasabo',
];
